// Code generated by protoc-gen-go.
// source: bq_table_name.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	bq_table_name.proto

It has these top-level messages:
*/
package main

import proto "github.com/golang/protobuf/proto"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

var E_TableName = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50000,
	Name:          "gen_bq_schema.table_name",
	Tag:           "bytes,50000,opt,name=table_name",
}

func init() {
	proto.RegisterExtension(E_TableName)
}
