// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bq_table.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BigQueryMessageOptions struct {
	// Specifies a name of table in BigQuery for the message.
	//
	// If not blank, indicates the message is a type of record to be stored into BigQuery.
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// If true, BigQuery field names will default to a field's JSON name,
	// not its original/proto field name.
	UseJsonNames bool `protobuf:"varint,2,opt,name=use_json_names,json=useJsonNames,proto3" json:"use_json_names,omitempty"`
	// If set adds defined extra fields to a JSON representation of the message.
	// Value format: "<field name>:<BigQuery field type>" for basic types
	// or "<field name>:RECORD:<protobuf type>" for message types.
	// "NULLABLE" by default, different mode may be set via optional suffix ":<mode>"
	ExtraFields          []string `protobuf:"bytes,3,rep,name=extra_fields,json=extraFields,proto3" json:"extra_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BigQueryMessageOptions) Reset()         { *m = BigQueryMessageOptions{} }
func (m *BigQueryMessageOptions) String() string { return proto.CompactTextString(m) }
func (*BigQueryMessageOptions) ProtoMessage()    {}
func (*BigQueryMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_54f9c1df63ca9ac7, []int{0}
}

func (m *BigQueryMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BigQueryMessageOptions.Unmarshal(m, b)
}
func (m *BigQueryMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BigQueryMessageOptions.Marshal(b, m, deterministic)
}
func (m *BigQueryMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BigQueryMessageOptions.Merge(m, src)
}
func (m *BigQueryMessageOptions) XXX_Size() int {
	return xxx_messageInfo_BigQueryMessageOptions.Size(m)
}
func (m *BigQueryMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_BigQueryMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_BigQueryMessageOptions proto.InternalMessageInfo

func (m *BigQueryMessageOptions) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

func (m *BigQueryMessageOptions) GetUseJsonNames() bool {
	if m != nil {
		return m.UseJsonNames
	}
	return false
}

func (m *BigQueryMessageOptions) GetExtraFields() []string {
	if m != nil {
		return m.ExtraFields
	}
	return nil
}

var E_BigqueryOpts = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*BigQueryMessageOptions)(nil),
	Field:         1021,
	Name:          "gen_bq_schema.bigquery_opts",
	Tag:           "bytes,1021,opt,name=bigquery_opts",
	Filename:      "bq_table.proto",
}

func init() {
	proto.RegisterType((*BigQueryMessageOptions)(nil), "gen_bq_schema.BigQueryMessageOptions")
	proto.RegisterExtension(E_BigqueryOpts)
}

func init() { proto.RegisterFile("bq_table.proto", fileDescriptor_54f9c1df63ca9ac7) }

var fileDescriptor_54f9c1df63ca9ac7 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xb1, 0x4b, 0x03, 0x31,
	0x14, 0xc6, 0x89, 0x05, 0xed, 0xa5, 0xd7, 0x0e, 0x19, 0xe4, 0x10, 0xc4, 0x28, 0x0a, 0x37, 0xa5,
	0xa0, 0x9b, 0x63, 0x07, 0x07, 0x41, 0x8b, 0x37, 0xba, 0x84, 0xa4, 0x7d, 0x8d, 0x91, 0xbb, 0x24,
	0x97, 0x97, 0x03, 0xdd, 0xfc, 0xc7, 0x05, 0x69, 0x8e, 0x0e, 0x05, 0xa7, 0xc0, 0x97, 0xef, 0xfd,
	0xf8, 0x7d, 0x74, 0xa1, 0x7b, 0x99, 0x94, 0x6e, 0x41, 0x84, 0xe8, 0x93, 0x67, 0x73, 0x03, 0x4e,
	0xea, 0x5e, 0xe2, 0xe6, 0x03, 0x3a, 0x75, 0xc1, 0x8d, 0xf7, 0xa6, 0x85, 0x65, 0xfe, 0xd4, 0xc3,
	0x6e, 0xb9, 0x05, 0xdc, 0x44, 0x1b, 0x92, 0x8f, 0xe3, 0xc1, 0xcd, 0x0f, 0xa1, 0xe7, 0x2b, 0x6b,
	0xde, 0x06, 0x88, 0xdf, 0x2f, 0x80, 0xa8, 0x0c, 0xac, 0x43, 0xb2, 0xde, 0x21, 0xbb, 0xa4, 0x34,
	0xa3, 0xa5, 0x53, 0x1d, 0x54, 0x84, 0x93, 0xba, 0x68, 0x8a, 0x9c, 0xbc, 0xaa, 0x0e, 0xd8, 0x2d,
	0x5d, 0x0c, 0x08, 0xf2, 0x13, 0xbd, 0xcb, 0x0d, 0xac, 0x4e, 0x38, 0xa9, 0xa7, 0x4d, 0x39, 0x20,
	0x3c, 0xa3, 0x77, 0xfb, 0x12, 0xb2, 0x6b, 0x5a, 0xc2, 0x57, 0x8a, 0x4a, 0xee, 0x2c, 0xb4, 0x5b,
	0xac, 0x26, 0x7c, 0x52, 0x17, 0xcd, 0x2c, 0x67, 0x4f, 0x39, 0x7a, 0x6c, 0xe9, 0x5c, 0x5b, 0xd3,
	0xef, 0x0d, 0xa4, 0x0f, 0x09, 0xd9, 0x95, 0x18, 0xb5, 0xc5, 0x41, 0x5b, 0x1c, 0x9b, 0x55, 0xbf,
	0x67, 0x9c, 0xd4, 0xb3, 0xfb, 0x3b, 0x71, 0xb4, 0x56, 0xfc, 0xbf, 0xa3, 0x29, 0x0f, 0xf4, 0x75,
	0x48, 0xb8, 0x9a, 0xbe, 0x9f, 0x66, 0x2c, 0xea, 0xf1, 0x7d, 0xf8, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0xff, 0xcf, 0x01, 0x93, 0x44, 0x01, 0x00, 0x00,
}
